### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by DarioDomiDE** [Vittel/AutoTagger#3]
Tests: Die Aktuellen überarbeiten, Dependencies mocken als Unit u. Acceptance-Tests verpacken, DI überhaupt erstmal ordentlich bastlen

**Comment by Vittel** [comment]
Habe ein xunit test projekt angelegt für komponenten tests. habe auch schon ein paar unserer consolen integration tests dorthin verschoben.
leider sind es nach wie vor integration tests.

**Comment by DarioDomiDE** [comment]
closed weil keine Priorisierung gerade

**Comment by Vittel** [comment]
Es sollte da eine XUnit Test Klasse incl. weniger Mocks geben, in die ich mal einige Methoden aus der Test-Console verschoben habe. 
Hier ist auch der einzige fall den ich bisher kennengelernt habe bei dem DI und IoC nicht äquivalent zu verwenden sind :) DI braucht man nicht für Unittests. Man kann DI verwenden wenn man seinen Code nach IoC so strukturiert, dass man ihn auch sauber testen kann. das geht Hand in Hand.
Aber tatsächlich war es zumindest bei meinem letzten Überblick alles im weitesten sinne nach diesem Paradigma ausgestaltet.

**Comment by DarioDomiDE** [comment]
ließ ma Slack ;)
