### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by DarioDomiDE** [Vittel/AutoTagger#4]
Hi,
ich hätte gerne wieder den UserInterface Service als REST API (ohne eigene Views).
Und das Frontend als separate Singlepage Application, welches die Rest API nutzt.
Frontend könnte man in Angular o.ä. basteln oder anfangs erstmal plain html.
Hosting müsste angepasst werden.

**Comment by tempel3** [comment]
Finde ich gut. 

Ich würde gerne folgendes probieren: https://docs.microsoft.com/de-de/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visual-studio

Dann kann ich den Controller auch gleich umbauen.

**Comment by Vittel** [comment]
@DarioDomiDE kann man machen! Swagger klingt auch gut. 
Bitte erstmal parallel zum derzeitigen Frontend entwickeln. Kann man später immer noch wegwerfen.

**Comment by DarioDomiDE** [comment]
closed weil umgesetzt
