### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by DarioDomiDE** [Vittel/AutoTagger#9]
Vorschlag Repo Renaming in ```InstaTagger``` oder ```InstagramTagger```?
oder wenn "Auto" drin bleiben soll, auch ```InstaAutoTagger``` oder  ```InstagramAutoTagger```?

**Comment by Vittel** [comment]
Soll später ggf. Für andere Sites auch funktionieren. Dementsprechend möchte ich das nicht auf Instagram einschränken.
Auch sehe ich keinen Anlass dafür?!

**Comment by DarioDomiDE** [comment]
Kann mit dem Namen einfach nichts anfangen.. was hälst du von "BestTagsFinder", "ImageTagger"?

**Comment by Vittel** [comment]
Macht für mich alles keinen unterschied. Soweit sich nicht etwas an der Ausrichtung ändert würde ich den namen einfach so belassen wie er ist.
Zumal es ja auch Aufwände mit sich bringt in der code-base. Ist einfach grad nicht sinnvoll.
